apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Top-level points RootSync at the hydrated default overlay output.
# This is what ConfigSync consumes.
resources:
  - manifests/config/default
